name: Build Test

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWD }}" | docker login https://ai-rebornsoft.asuscomm.com:5000 -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker Build and Push
        run: |
          current_time=$(date +"%Y%m%d%H%M%S")
          registry=ai-rebornsoft.asuscomm.com:5000/api
          docker build -t $(registry):$(current_time) -t $(registry):latest .
          docker push $(registry):$(current_time)
          docker push $(registry):latest
          docker logout

      
